### ISSUE TITLE
bug: line that is entirely a comment compresses to a space

### ISSUE THREAD

**Issue by thenomain** [Digibear-io/mush-format#21]
**Describe the bug**
A line that is entirely a comment compresses to a space

**To Reproduce**
```
think 
    [setr(a,test)]
// that was a test, here's the rest of it
    [setr(b,aloha)]
```

**Expected behavior**
```
think [setr(a,test)][setr(b,aloha)]
```

**What it does**
```
think [setr(a,test)] [setr(b,aloha)]
```

**Additional comments**
If there was a trailing space on after the first `]` then yes, keep that. In this instance, the comment line is inserting an unwanted space.

**Comment by lcanady** [comment]
Fixed with the last push!  Thanks for being vigilant as usual! :)
